version: '3.9'

services:
  # Main Application
  app:
    container_name: progressSoftApp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - POSTGRES_DB=fxwarehouse
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/fxwarehouse
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - warehouse
    depends_on:
      - postgres-db

  # Database
  postgres-db:
    container_name: postgres-warehouse
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=fxwarehouse
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - warehouse

networks:
  warehouse:
    driver: bridge

volumes:
  postgres-data:
    driver: local
