server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fxwarehouse
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

logging:
  level:
    com.progressoft: DEBUG
